name: Dockerized Full Stack CI/CD

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create Backend .env File
        run: |
          echo "PORT=5000" > backend/.env
          echo "DB_HOST=postgres-db" >> backend/.env
          echo "DB_USER=postgres" >> backend/.env
          echo "DB_PASSWORD=postgres" >> backend/.env
          echo "DB_NAME=appdb" >> backend/.env

      - name: Verify Docker Version
        run: docker --version

      - name: Verify Docker Compose Version
        run: docker compose version

      - name: Build Docker Containers
        run: docker compose build

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Verify Running Containers
        run: docker ps